spring.application.name=CraveCart
spring.datasource.url=jdbc:mysql://localhost:3306/cravecart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true