spring.application.name=CraveCart
spring.datasource.url=jdbc:mysql://localhost:3306/cravecart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Google OAuth2 Settings
spring.security.oauth2.client.registration.google.client-id=362647837017-df092r8ei7ubq82dq4icgg416d7css2p.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
# Email Settings (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=charithachiranjeewa@gmail.com
spring.mail.password=tigs fdck qute wwip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
